import pathlib

import pandas


def generate_data_list(data_dir: pathlib.Path, data_count: dict, class_num: int):
    """
    Generate a data_list.hf file that contains the information of whole dataset.

    Shouldn't use it before all grams are generated by MATLAB code.

    :param data_dir: The path to the folder that contains all grams (no sub-folder).
    :param data_count: The number range of every experiment variable.
    :param class_num: The number of classes.
    """
    
    if not data_dir.exists() or not data_dir.is_dir():
        raise FileNotFoundError("Can not find data folder {name}".format(name = data_dir))
    
    erroneous_data = ["gym_gyy_5+b_8", "gym_gyy_b5+_9"]
    
    dataset_path = data_dir / 'data_list.hf'
    
    with pandas.HDFStore(str(dataset_path), mode = 'w') as store:
        data = []
        for rom_ind in range(1, data_count['room'] + 1):
            for usr_ind in range(1, data_count['user'] + 1):
                for pos_ind in range(1, data_count['positions']+1):
                    for rep_ind in range(1, data_count['repetition'] + 1):
                        sample_name = str(rom_ind) + '-' + str(usr_ind) + '-'  + str(pos_ind) + '-' + str(rep_ind)
                        rooms = ["corridor", "gym", "room201", "room420"]
                        users = ["cs", "cx", "fxp", "gyy", "ljc", "wzy", "xbz", "zhb"]
                        postions = ["1+1", "2+2", "3+3", "4+c", "4e", "5+b", "5f", "11+", "22+", "33+",
                                    "a+g", "ag+", "b5+", "c+c", "c4+", "cc+", "d+d", "dd+", "e+e", "e4",
                                    "ee+", "f5", "g+a", "ga+"]
                        sample_real_name = rooms[rom_ind-1] + '_'  + users[usr_ind-1] + '_' +  postions[pos_ind-1] + '_'  + str(rep_ind)
                        # skip erroneous data
                        if sample_real_name in erroneous_data:
                            print('Skip erroneous data', sample_real_name)
                            continue
                                
                        sample_name += '.mat'
                        sample_real_name += '.mat'
                                
                        sample_path = data_dir / sample_real_name
                        if not sample_path.exists() or not sample_path.is_file():
                            raise FileNotFoundError("Can not find sample {name}".format(name = sample_real_name))
                                
                        # indices in python are expected to start from 0 instead of 1
                        data.append([rom_ind - 1, usr_ind - 1, pos_ind - 1, rep_ind - 1, sample_real_name])
            
        data_frame = pandas.DataFrame(data, columns = ['room', 'user', 'position', 'repetition', 'gram'])
        store.put('data', data_frame)
        del data, data_frame
        
        # empty activity samples were collected with user_ind == 1/2 and pos_ind == 1
        # data = []
        # for rom_ind in range(1, data_count['room'] + 1):
        #     for usr_ind in range(1, data_count['user'] + 1):
        #         for rep_ind in range(1, data_count['repetition'] + 1):
        #             if not (usr_ind == 1 or (rom_ind == 4 and usr_ind == 2)):
        #                 continue
                    
        #             sample_name = str(rom_ind) + '-' + str(usr_ind) + '-' + str(1) + '-' + str(8) + '-' + str(rep_ind)
        #             sample_name += '.mat'
                    
        #             sample_path = data_dir / sample_name
        #             if not sample_path.exists() or not sample_path.is_file():
        #                 raise FileNotFoundError("Can not find sample {name}".format(name = sample_name))
                    
        #             # indices in python are expected to start from 0 instead of 1
        #             data.append([rom_ind - 1, rep_ind - 1, sample_name])
        
        # data_frame = pandas.DataFrame(data, columns = ['room', 'repetition', 'gram'])
        # store.put('empty', data_frame)
        # del data, data_frame
        
        # # random activity wasn't collected in room 1
        # data = []
        # for rom_ind in range(1, data_count['room'] + 1):
        #     for usr_ind in range(1, data_count['user'] + 1):
        #         for pos_ind in range(1, data_count['position'] + 1):
        #             for rep_ind in range(1, data_count['repetition'] + 1):
        #                 if rom_ind == 1:
        #                     # random activity wasn't collected in room 1
        #                     continue
                        
        #                 sample_name = str(rom_ind) + '-' + str(usr_ind) + '-' + str(pos_ind) + '-' + str(9) + '-' + str(
        #                         rep_ind)
        #                 sample_name += '.mat'
                        
        #                 sample_path = data_dir / sample_name
        #                 if not sample_path.exists() or not sample_path.is_file():
        #                     raise FileNotFoundError("Can not find sample {name}".format(name = sample_name))
                        
        #                 # indices in python are expected to start from 0 instead of 1
        #                 data.append([rom_ind - 1, usr_ind - 1, (pos_ind - 1) * data_count['repetition'] + (rep_ind - 1),
        #                              sample_name])
        
        # data_frame = pandas.DataFrame(data, columns = ['room', 'user', 'repetition', 'gram'])
        # store.put('random', data_frame)
        # del data, data_frame


if __name__ == '__main__':
    from configs import default_configs as conf
    
    generate_data_list(conf.data_dir, conf.data_count, conf.class_num)
